export type City = { name: string; tz: string; label: string };

export const CITIES: City[] = [
  { name: "San Francisco", tz: "America/Los_Angeles", label: "San Francisco (PT)" },
  { name: "Los Angeles", tz: "America/Los_Angeles", label: "Los Angeles (PT)" },
  { name: "Denver", tz: "America/Denver", label: "Denver (MT)" },
  { name: "Chicago", tz: "America/Chicago", label: "Chicago (CT)" },
  { name: "New York", tz: "America/New_York", label: "New York (ET)" },
  { name: "Toronto", tz: "America/Toronto", label: "Toronto" },
  { name: "Mexico City", tz: "America/Mexico_City", label: "Mexico City" },
  { name: "São Paulo", tz: "America/Sao_Paulo", label: "São Paulo" },
  { name: "Buenos Aires", tz: "America/Argentina/Buenos_Aires", label: "Buenos Aires" },
  { name: "London", tz: "Europe/London", label: "London" },
  { name: "Dublin", tz: "Europe/Dublin", label: "Dublin" },
  { name: "Lisbon", tz: "Europe/Lisbon", label: "Lisbon" },
  { name: "Paris", tz: "Europe/Paris", label: "Paris" },
  { name: "Berlin", tz: "Europe/Berlin", label: "Berlin" },
  { name: "Amsterdam", tz: "Europe/Amsterdam", label: "Amsterdam" },
  { name: "Madrid", tz: "Europe/Madrid", label: "Madrid" },
  { name: "Rome", tz: "Europe/Rome", label: "Rome" },
  { name: "Stockholm", tz: "Europe/Stockholm", label: "Stockholm" },
  { name: "Warsaw", tz: "Europe/Warsaw", label: "Warsaw" },
  { name: "Athens", tz: "Europe/Athens", label: "Athens" },
  { name: "Istanbul", tz: "Europe/Istanbul", label: "Istanbul" },
  { name: "Moscow", tz: "Europe/Moscow", label: "Moscow" },
  { name: "Cairo", tz: "Africa/Cairo", label: "Cairo" },
  { name: "Lagos", tz: "Africa/Lagos", label: "Lagos" },
  { name: "Johannesburg", tz: "Africa/Johannesburg", label: "Johannesburg" },
  { name: "Nairobi", tz: "Africa/Nairobi", label: "Nairobi" },
  { name: "Dubai", tz: "Asia/Dubai", label: "Dubai" },
  { name: "Tel Aviv", tz: "Asia/Jerusalem", label: "Tel Aviv" },
  { name: "Riyadh", tz: "Asia/Riyadh", label: "Riyadh" },
  { name: "Karachi", tz: "Asia/Karachi", label: "Karachi" },
  { name: "Mumbai", tz: "Asia/Kolkata", label: "Mumbai (IST)" },
  { name: "Bangalore", tz: "Asia/Kolkata", label: "Bangalore (IST)" },
  { name: "Delhi", tz: "Asia/Kolkata", label: "Delhi (IST)" },
  { name: "Dhaka", tz: "Asia/Dhaka", label: "Dhaka" },
  { name: "Bangkok", tz: "Asia/Bangkok", label: "Bangkok" },
  { name: "Jakarta", tz: "Asia/Jakarta", label: "Jakarta" },
  { name: "Singapore", tz: "Asia/Singapore", label: "Singapore" },
  { name: "Hong Kong", tz: "Asia/Hong_Kong", label: "Hong Kong" },
  { name: "Shanghai", tz: "Asia/Shanghai", label: "Shanghai" },
  { name: "Beijing", tz: "Asia/Shanghai", label: "Beijing" },
  { name: "Taipei", tz: "Asia/Taipei", label: "Taipei" },
  { name: "Seoul", tz: "Asia/Seoul", label: "Seoul" },
  { name: "Tokyo", tz: "Asia/Tokyo", label: "Tokyo" },
  { name: "Sydney", tz: "Australia/Sydney", label: "Sydney" },
  { name: "Melbourne", tz: "Australia/Melbourne", label: "Melbourne" },
  { name: "Perth", tz: "Australia/Perth", label: "Perth" },
  { name: "Auckland", tz: "Pacific/Auckland", label: "Auckland" },
  { name: "Honolulu", tz: "Pacific/Honolulu", label: "Honolulu" },
];
